### ISSUE TITLE
Verify img files from docker hub checksum hash

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#107]
By going along the line https://github.com/moby/moby/blob/master/pkg/tarsum/tarsum.go#L4 (and reusing the library) it should be possible to build a standalone-tool which generates a checksum out of an img file, which in turn we can compare back with the docker image checksum.

This card is a spike, to assess if that mechanism is a viable solution, and that can guarantee that the recomposed images (which are used to boot a cos derivatives) are identical (their blobs) to the one pulled from dockerhub.

The context of this card is: we should be able to create standalone tool capable of computing the hash of an image file content (`.img`)

We should create follow-up cards if the mechanism is a viable solution to: create the real cli, and implement the changes to our installation/upgrade scripts ( https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/installer/upgrade.sh#L122 and https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/installer/upgrade.sh#L81 )

Part of #95

**Comment by Itxaka** [comment]
Several things that I found during the spike:

 - In order to have consistent tar files we need to set the flag `--format=ustar` as that makes them reproducible, otherwise we get the default pax/posix format which includes several fields that will never match[0]
 - This above is subject to changes as it may be possible to ignore the paxheaders on doing the checksum, but I havent found a way to do so without reimplementing the whole thing.
 - If comparing docker images (instead of build images) we need to decompress and checksum the layer.tar file which is the one to actually contain the files. The rest of the files in the docker image are subject to modifications which would never match like timestamps.
 - I created a small CLI[2] to check tarsums using the library from moby[1]. This lib is unable to open tar files with the ustar format as it expect pax headers. It may be possible to work around this but I havent investigated further but it migth make sense to reimplement some of its part ourselves if we want to ignore the headers stuff


[0] https://en.wikipedia.org/wiki/Tar_(computing)#POSIX.1-2001/pax
[1] https://github.com/moby/moby/blob/master/pkg/tarsum/tarsum.go
[2] https://github.com/Itxaka/fusionkit

**Comment by davidcassany** [comment]
If all this is getting too complex by using the moby utilities I would explore mtree utility. The go port is available and stable since a while, if I am not mistaken this is what umoci and other OCI related tools use, see https://github.com/vbatts/go-mtree#tar-form, to my eyes this looks like pretty similar what we are trying to achieve.

**Comment by Itxaka** [comment]
That worked beautifully.

We still need to extract the layer.tar in case its a dockerfile we are testing, but it generated the proper checksums for both files correctly

**Comment by mudler** [comment]
Yup, I don't think indeed we should have strings attached to the moby library, that was meant likely as a starting point, if go-mtree does exactly what we need, we should just consume that :+1:

**Comment by Itxaka** [comment]
This seems doable and should be done, creating a follow up card for the implementation!
