### ISSUE TITLE
cloud-init: support resizing on MBR partition tables

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1075]
Seems the [automatic resizing from the cloud-init examples](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/examples/rpi/files/system/oem/01_auto_expand.yaml) in the rpi(also odroidc2, probably) images doesn't work. I get a silent exit status 2. However, the generated command seems correct (sgdisk .. ) which correctly identifies the partition number.

Follow up of #1023

_Originally posted by @mudler in https://github.com/rancher-sandbox/cOS-toolkit/issues/1023#issuecomment-1015521528_

**Comment by mudler** [comment]
@davidcassany could it be related that with sgdisk is gpt the prefered partition table layout? or should not actually be an issue? I'm just wondering, because most of the resizing scenario tests we perform on EFI, but we don't really test outside of it

**Comment by davidcassany** [comment]
Isn't RPi using the MSDOS partition tables? If so, then it won't work. Layout plugin only works for GPT partition tables as it is based on sgdisk. 

The real fix for that is using the partitioner package from elemental-cli in yip as it supports MSDOS and GPT. Indeed updating yip layout plugin to relay on elemental-cli partitioner package has been my midterm intention since we started elemental-cli. It should be relatively simple to do so as the API in partitioner module is intentionally copying the layout yip plugin for that exact purpose.

**Comment by mudler** [comment]
ok, treating it as a feature request then as we never actually supported this before in MBR

**Comment by mudler** [comment]
Ano

> Isn't RPi using the MSDOS partition tables? If so, then it won't work. Layout plugin only works for GPT partition tables as it is based on sgdisk.
> 
> The real fix for that is using the partitioner package from elemental-cli in yip as it supports MSDOS and GPT. Indeed updating yip layout plugin to relay on elemental-cli partitioner package has been my midterm intention since we started elemental-cli. It should be relatively simple to do so as the API in partitioner module is intentionally copying the layout yip plugin for that exact purpose.

Another way  is also to consume directly the partitioner from elemental-cli in the elemental-cli cloud init runner, but I'm not sure if it already works as a drop-in replacement for the layout plugin currently in `yip`, anyhow both ways sounds fine!

**Comment by davidcassany** [comment]
> Another way is also to consume directly the partitioner from elemental-cli in the elemental-cli cloud init runner, but I'm not sure if it already works as a drop-in replacement for the layout plugin currently in `yip`

I don't think so, as I believe console interface and probably few other details are not fully aligned. Anyway it is worth finding the best way to express or sort out this dependencies since having elemental-cli requiring yip and yip requiring some elemental-cli package looks like leading to confusions or strange circular dependency issues.

**Comment by mudler** [comment]
> Anyway it is worth finding the best way to express or sort out this dependencies since having elemental-cli requiring yip and yip requiring some elemental-cli package looks like leading to confusions or strange circular dependency issues.

Yes indeed, better or `yip` takes the 'extended' layout plugin code, or either elemental-cli just replaces with its own, leaving the yip layout plugin as it is currently. I'd suggest just elemental-cli to drop their own to avoid code dups (unless we split the layout code in a standalone lib..)
