### ISSUE TITLE
Test and boot the PoC img in Google Cloud

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#222]
From the outcome of #218 fine tune the image so that it is also bootable in Google Cloud.

Requires #218

## Requirements

 - [x] Fine tune image so it can boot in gce -> #406 
 - [x] Document steps taken and needed to boot the image -> https://github.com/rancher-sandbox/cos-toolkit-docs/pull/4

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/406

Was able to upload the image and create an VM based of that with user-data that booted to recovery.

To create an image based of the vanilla image generated on that PR:

```
$ gsutil cp cos-vanilla-0.5.8+2.tar.gz gs://YOURBUCKET/
$ gcloud compute images create cos-vanilla-0-5-8plus2 --project=YOURPROJECT --source-uri=YOURBUCKET/cos-vanilla-0.5.8\+2.tar.gz --storage-location=eu --guest-os-features=UEFI_COMPATIBLE --family=cos-vanilla --labels="flavor=vanilla,name=cos,version=0-5-8_2"

```

where:
 - --guest-os-features=UEFI_COMPATIBLE is required so machines with this image boot with UEFI, otherwise it tries legacy boot and it fails
 - --family=cos-vanilla : `The family of the image. When creating an instance or disk, specifying
        a family will cause the latest non-deprecated image in the family to be
        used.` so this is used to filter if you were to choose your boot image as cos-vanilla it would pick the latest version.
 - --labels: for easy filtering.

Then you can create a vm based of that image and pass the user-data that you want (see images/user-data.yaml for an example) and it will boot and deploy cos.

**Comment by mudler** [comment]
@Itxaka maybe we can add the instructions of https://github.com/rancher-sandbox/cOS-toolkit/issues/222#issuecomment-879787526 on how to boot on GCP to our docs ? (as we have them now!) :smile:

**Comment by Itxaka** [comment]
Makes sense, lets see if I can send that today if I get to finish the azure stuff
