### ISSUE TITLE
Packages to add to the rootfs image

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#30]
For the ones coming from zypper, should be as simple as adding them here: https://github.com/mudler/cOS/blob/85e764da2ab6698d9c3d216de0e55834a8ee25d7/packages/tumbleweed/definition.yaml#L5

- [ ]        conntrack-tools
- [x]        curl
- [x]        dosfstools
- [x]        e2fsprogs
- [ ]        findutils
- [ ]        haveged
- [x]        iproute2
- [ ]        iptables
- [ ]        lsscsi
- [ ]        lvm2
- [ ]        mdadm
- [ ]        multipath-tools
- [ ]        nfs-utils
- [ ]        open-iscsi
- [ ]        open-vm-tools
- [ ]        python-azure-agent*
- [ ]        qemu-guest-agent
- [ ]        rng-tools
- [ ]        rancher-agent

**Comment by davidcassany** [comment]
> We should check anyhow if we can reduce their footprint, by removing extra files which are not needed

Some of it can be done a RPM macro level and libzypp conf level. One can avoid the installation of files in certain folder, avoid the installation of file marked as doc or translations to other languages. This not super effective as it needs to be generic for every package but relatively simple to maintain.

On the other side I am fine trying to reduce the image footprint. I spended myself quite some time trying to make leap and sle containers small and I ended up to the conclusion that most of this work should be done on the package itself at distro level. Anyway, that makes me wonder if we are under some expectations regarding the size of the image, otherwise I would not put pressure now on making it smaller, it feels like a pre-optimization.

**Comment by mudler** [comment]
> > We should check anyhow if we can reduce their footprint, by removing extra files which are not needed
> 
> Some of it can be done a RPM macro level and libzypp conf level. One can avoid the installation of files in certain folder, avoid the installation of file marked as doc or translations to other languages. This not super effective as it needs to be generic for every package but relatively simple to maintain.

:+1: 
> 
> On the other side I am fine trying to reduce the image footprint. I spended myself quite some time trying to make leap and sle containers small and I ended up to the conclusion that most of this work should be done on the package itself at distro level. Anyway, that makes me wonder if we are under some expectations regarding the size of the image, otherwise I would not put pressure now on making it smaller, it feels like a pre-optimization.

Yup I agree, and there is no real pressure on it indeed. it's mostly a note to keep in mind for the future being. The thing is that we won't need `zypper` or `rpm`, for example to be available on the installable image (because upgrades needs to happen in one docker image only, see #5  and #21 ), which is kinda problematic when I've tried to do that from zypper/rpm itself. 

That's why you can see `excludes` in luet specfiles being used in the tumbleweed image definition (the one that gets installed in the system) like here https://github.com/mudler/cOS/blob/master/packages/tumbleweed/build.yaml#L71. 

In that case it is also stripping everything in `/usr/include` too, and that should be more than enough for the moment,.

Anyhow we have #26 already tracking the shrinking of image size, so nothing much to worry about for now

**Comment by mudler** [comment]
Most of those packages are added in this branch: https://github.com/rancher-sandbox/cOS/tree/cos-feature-k3s where I'm trying to run k3s/longhorn/harvester on top of cOS (as longhorn required iscsi)
