### ISSUE TITLE
Use GRUB instead of syslinux in the iso live image

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#521]
It's much easier to consistently use the same bootloader in all places, and also GRUB is much more flexible in terms of #520 

**Is your feature request related to a problem? Please describe.**
Currently we use syslinux to build our ISOs, using GRUB would help us in the long-term to have a consistent mechanism across live and the installed system.

**Describe the solution you'd like**
Using GRUB in place of syslinux, with the documentation updated as needed

**Comment by davidcassany** [comment]
This card is bigger than I had expected. It turns that `luet-makeiso` is quite coupled to `syslinux` (see https://github.com/mudler/luet-makeiso/blob/master/pkg/burner/iso.go), so adding support for grub2 while being backward compatible is a relevant refactor task in [mudler/luet-makeiso](https://github.com/mudler/luet-makeiso).

**Comment by davidcassany** [comment]
Moving it back to TODO. I prefer to tackle #520 and #430 before diving into this, since it might take a while and the other tasks are smaller and directly facing our users. I'll try to make a simple documentation about the customization of boot entries of the ISO  by mostly overwriting files so if we finally run this current task re-adapting the docs will be easy.

**Comment by mudler** [comment]
makeiso 0.3.5 have gained support to specify BootFile, BootCatalog and IsoHybridMBR:

```yaml
boot_file: ...
boot_catalog: ...
isohybrid_mbr: ...
```

**Comment by davidcassany** [comment]
> makeiso 0.3.5 have gained support to specify BootFile, BootCatalog and IsoHybridMBR:

Good! Gonna check if this is already enough, it might be.
