### ISSUE TITLE
Create an `elemental` golang project skeleton

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#881]
Create a golang project skeleton that must include:

- [x] github repository (`elemental`) under rancher-sandbox organization
- [x] configuration files parsing (viper ?)
- [x] cli flag and subcommands parsing (cobra(?), see commands #108)
- [x] unit tests
- [x] releasing workflow (goreleases)
- [x] tests and releases on github actions
- [x] spec file inside cos-toolkit

## Notes
As a reference [luet](https://github.com/mudler/luet) project makes use a similar stack (viper, goreleases, cobra, etc.): [Viper custom config unmarshalling](https://github.com/mudler/luet/blob/master/cmd/root.go#L84), [initialization](https://github.com/mudler/luet/blob/ba0551caab45d334b0694f5778b6f6c77cbc0ec6/cmd/util/config.go#L158)

**Comment by Itxaka** [comment]
mostly done as the skeleton is simple enough: https://github.com/rancher-sandbox/elemental-cli

**Comment by Itxaka** [comment]
We need to decide on which file/files are gonna contain the configuration. @davidcassany @mudler @dragonchaser

**Comment by mudler** [comment]
I'm trying to identify the configuration by "category":

We have two configuration inputs layer, one for the build process, and one for runtime.

For the build process, we have the [manifest file](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/manifest.yaml) which we should parse in order to build our pieces internally.
If we consider e.g. ISO generation and ARM Images they take also container image references as input (which we can handle individually, via CLI args)

For the runtime, we have https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/general_configuration/ , mainly should be about reading the config from a file which is an environment file which contains variables ( I can suggest github.com/joho/godotenv, which `yip` is leveraging for the task ), again some runtime CLI commands (like `install`, `reset`, etc) will take individual args that might override general configurations.

A reference on unmarshalling things in viper is https://github.com/mudler/luet/blob/master/cmd/root.go#L84, a similar approach could be taken

**Comment by Itxaka** [comment]
@mudler If I understood correctly, viper itself should be able to load the config file from a file which contains variables and parse that directly? As long as we set the proper configType, and point to the file it should be loaded.

```
NOTE [since 1.6]: You can also have a file without an extension and specify the format programmaticaly. For those configuration files that lie in the home of the user without any extension like .bashrc
```

**Comment by mudler** [comment]
> @mudler If I understood correctly, viper itself should be able to load the config file from a file which contains variables and parse that directly? As long as we set the proper configType, and point to the file it should be loaded.
> 
> ```
> NOTE [since 1.6]: You can also have a file without an extension and specify the format programmaticaly. For those configuration files that lie in the home of the user without any extension like .bashrc
> ```

Even better then!

**Comment by davidcassany** [comment]
IMHO I'd go for some structured configuration files (yaml, toml, xml... I do not have strong preference on which) and avoid environment files. Then we can explicitly allow within the client the environment variables we want to allow and have full freedom to explicitly overwrite or not whatever is defined in a config file beyond defaults. Also, if we have some structured config file it is easy, in general, to define all defaults together with some sort of schema to sanitize the config. 

Also there is the additional benefit of being able to version the schema and allow config file refactors while keeping backward compatibility.

Doesn't need to be very sophisticated now (e.g. well defined versioned schema) as if we start using some structured data from the beginning all those details can be added little by little later on.

What you think? 

Also I believe there are three steps to consider for config. Build time, run time and install time. Note install time could be considered runtime or build time depending the use case (installing from ISO or building raw images), so something to keep in mind.

**Comment by Itxaka** [comment]
I would also prefer some structured config file that cannot be loaded as environment vars. Like a cos.yaml file wont do anything if you do `source cos.yaml`, and that makes it clear which one is the config and which vars can be overridable via env var.

I mean, the manifest file is a good example of this, we can keep configs for a lot of different things in there, and we are sure they wont collide, and we can easily expand it (like we did with the arches).

So my vote would be to have a dedicated config file, easily overridable (`/etc/cos/config.d/`) by derivatives.

For build, I would keep the manifest, maybe restructure in the future to make categories or whatever so its clear what part are those, but would not touch it that much.

**Comment by davidcassany** [comment]
> So my vote would be to have a dedicated config file, easily overridable (`/etc/cos/config.d/`) by derivatives.

:+1:

**Comment by mudler** [comment]
> also it would help to sync all the config in one place as we currently have 3 places:
> 
> ```
>     /etc/environment
>     /etc/os-release
>     /etc/cos/config
> ```

I'm fine with structured config file, that's why we should keep the manifest.yaml in mind as use case, however, the ability to read configuration files  as  documented https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/general_configuration/ should be kept as a feature. Allowing to store configurations in the os-release file is quite handy when writing derivatives.

**Comment by Itxaka** [comment]
> Why avoiding config vars via environment? I do see this as a huge limitation. Viper already allows to bind environment configurations with config file (yamls, etc) without much hassle.

No, I mean, the config file should be structured which completely forbids it to be loaded as env vars. Im ok with env vars, but for generic things that work across the full suite, i.e. quiet, assume yes, debug, etc...

As soon as the cli starts growing we are gonna need to have a structured config file to separate the different commands, arches, configs, etc... like we did on the CI config, and as we did on the manifest. Growing those files organically was easier and the end results is much clearer. 

Introducing complexity in a config system in which you have to support env vars is a greek tragedy. How do you override a config that is down `installer -> x86_64 -> image`?? Do you start growing the complexity in vars and in your config system to provide all of those for.... no upsides? 

Why not plain config file, overridable generic flags that work across the whole app? That way you get the best of both worlds. But supporting each config value with a similar env var means that your grow is limited by the complexity of your own configuration!

I know env vars are used widely, but flag only apps are also everywhere. Doesn't mean that any of those is wrong, but the approach they took is different. Things like zypper or qemu have hundreds of commands, subcommands and flags and don't use env vars at all. It would be a mess if they had to map every config into an env var, but zypper is used thousands of times daily (also inside docker, we use it ourselves :P) and nobody seems to have any issues with using the flags :D


Im not against env vars (well...maybe a bit because of their actual use). Im more worried about our future supporting a complex system that doesn't need to, especially when we now that from one day to another we may need to support X or introduce Y and that migth require new options, new configs, new subcommands. I pray for us if we go with flat, plain env file :crying_cat_face:

**Comment by mudler** [comment]
> > Why avoiding config vars via environment? I do see this as a huge limitation. Viper already allows to bind environment configurations with config file (yamls, etc) without much hassle.
> 
> No, I mean, the config file should be structured which completely forbids it to be loaded as env vars. Im ok with env vars, but for generic things that work across the full suite, i.e. quiet, assume yes, debug, etc...

Ok then I misunderstood, makes perfectly sense :thumbsup:

> Introducing complexity in a config system in which you have to support env vars is a greek tragedy. How do you override a config that is down `installer -> x86_64 -> image`?? Do you start growing the complexity in vars and in your config system to provide all of those for.... no upsides?

I do agree here, especially the `manifest` file might have no value at all to specify via env var but even in this specific case would be handled already (by viper) , no need to go to that detail level!

**Comment by davidcassany** [comment]
I am with @Itxaka no need to forbid env vars, and they make complete sense in some cases (that's one of the reasons to code entrypoint scripts in containerized apps), just avoid loading config files as environment variables and avoid magically mapping variables loaded from a file to the scope of our application logic. I'd rather prefer having some explicit logic in our application that checks for the existence of specific environment variables and reacts according to that.

Also, I am not sure if this is required for the skeleton, but I'd like to introduce some sort of templating utility. Something as I am doing in #894 with the `cos-config-tmpl` package. I'd expect it to be replaced by some utility included within the elemental client. So have in mind that we are likely to need some templating engine in this tool, I'd say it has no impact in skeleton, but I have no experience on golang templating engines. Probably worth checking which is the simple obvious choice.

**Comment by Itxaka** [comment]
So then we agree to go with structured config file (/etc/elemental/config.yaml?) and overrides for derivatives (/etc/elemental/config.d/*.yaml?) and ALSO have env vars for some of them values (when it makes sense for automation, CI, etc..?)

Also good idea with the templating, gomplate is what we use for generating the CI, luet uses the helm template engine I believe. I dont care which one to use thought, I think gomplate is more widely used?+


In any case, as this cli is currently non usable, we can change whatever we want for now so it should be ok to change all this stuff at any given moment until we have something that can substitute at least the installer/upgrade/rebrand stuff as a MVP (yip, makeiso et al seem more difficult to me)

**Comment by Itxaka** [comment]
Updated https://github.com/rancher-sandbox/elemental-cli with config files, default paths, override by env vars (only for plain values in the config files) and tests.

I would say this is done, the skeleton is done, CI is in place, tests are in place for whatever code is in there, etc...

Should probably close this as all objectives are filled.

**Comment by mudler** [comment]
@Itxaka we are missing the spec file in cOS toolkit to consume it :smiling_face_with_tear:

**Comment by mudler** [comment]
having a look: also missing tests running inside the GHA workflow

**Comment by Itxaka** [comment]
where the hell did my tests go??? 

I promise I had a CI action for them :/

**Comment by Itxaka** [comment]
Test merged back, I forgot to add them :D

Package added to cos-toolkit: https://github.com/rancher-sandbox/cOS-toolkit/pull/911
